# Generated by Django 5.1.1 on 2024-09-12 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BMSDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('token', models.CharField(max_length=255)),
                ('polling_interval', models.IntegerField(default=60)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bms_devices', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'BMS Devices',
            },
        ),
        migrations.CreateModel(
            name='Dataset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.JSONField()),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('bms', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to='core.bmsdevice')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='datasets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date'],
            },
        ),
        migrations.AddIndex(
            model_name='bmsdevice',
            index=models.Index(fields=['token'], name='core_bmsdev_token_d685f6_idx'),
        ),
    ]
