# Generated by Django 5.1.1 on 2024-09-11 01:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bmsdevice',
            options={'verbose_name': 'BMS Devices'},
        ),
        migrations.AddField(
            model_name='bmsdevice',
            name='polling_interval',
            field=models.IntegerField(default=60),
        ),
    ]
